version: '3'
services:
  web-app:
    build: web_application
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - "./web_application/src:/web-application/src"
    depends_on: 
      - "db"
  db:
    build: ./db
    ports: 
      - "3306:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=abc123"
      - "MYSQL_DATABASE=myDB"